/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ejercicios11

import kotlin.random.Random

fun main() {
    println(generaNumeros(Random.nextInt(0,10)))
    println(generaMayuscula())
    println(generaMinuscula())
    println(generaContraseña(10))
}
fun generaNumeros(x: Int) : String{
    var csa = ""
    for (i in (0..<x).reversed())
        csa += i

    return csa
}
fun generaMayuscula() : String{
    val sb = StringBuilder()
    for (i in ('A'..'Z')){
        if(Random.nextBoolean()){
            val pos = Random.nextInt(sb.length+1)
            sb.insert(pos,i)
        }
    }
    return sb.toString()
}
fun generaMinuscula() : String{
    val sb = StringBuilder()
    for (i in ('a'..'z')){
        if(Random.nextBoolean()){
            val pos = Random.nextInt(sb.length+1)
            sb.insert(pos,i)
        }
    }
    return sb.toString()
}
fun generaContraseña(tamaño:Int): String {
    val sb = StringBuilder()
    val mayus = generaMayuscula()
    val minus = generaMinuscula()
    for (i in 0 until tamaño) {
        if (Random.nextBoolean())
            sb.append(mayus[Random.nextInt(mayus.length)])
        else
            sb.append(minus[Random.nextInt(minus.length)])
    }

    return sb.toString()
}